<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Movie\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaEntities\Domain.csproj" />
    <ProjectReference Include="..\NediaLibrary.Repositories\MediaLibrary.Repositories.csproj" />
  </ItemGroup>

</Project>
