<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Movie\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaEntities\MediaLibrary.Entities.csproj" />
    <ProjectReference Include="..\MediaLibrary.Common\MediaLibrary.Common.csproj" />
    <ProjectReference Include="..\NediaLibrary.Repositories\MediaLibrary.Repositories.csproj" />
  </ItemGroup>

</Project>
