<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>aspnet-MediaLibrary-C7085D69-2D80-4744-9AE9-7D3FC28AA895</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\20181020173344_test.cs" />
    <Compile Remove="Data\Migrations\20181020173344_test.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BeginCollectionItemCore" Version="1.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" PrivateAssets="All" />
  </ItemGroup>

</Project>
