// <auto-generated />
using System;
using MediaLibrary.Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaLibrary.Entities.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181018225220_adding seed data")]
    partial class addingseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaLibrary.Models.Audio.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlbumFormatAudioFormatID");

                    b.Property<string>("AlbumTitle")
                        .IsRequired();

                    b.HasKey("AlbumID");

                    b.HasIndex("AlbumFormatAudioFormatID");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumID = 1, AlbumFormatAudioFormatID = 1, AlbumTitle = "Boney M Gold" }
                    );
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.AlbumSong", b =>
                {
                    b.Property<int>("AlbumID");

                    b.Property<int>("SongID");

                    b.Property<string>("Note");

                    b.Property<DateTime>("PlayTime");

                    b.HasKey("AlbumID", "SongID");

                    b.HasIndex("SongID");

                    b.ToTable("AlbumSongs");

                    b.HasData(
                        new { AlbumID = 1, SongID = 1, PlayTime = new DateTime(2018, 10, 19, 4, 15, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 2, PlayTime = new DateTime(2018, 10, 19, 3, 26, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 3, PlayTime = new DateTime(2018, 10, 19, 3, 56, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 4, PlayTime = new DateTime(2018, 10, 19, 4, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 5, PlayTime = new DateTime(2018, 10, 19, 4, 24, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 6, PlayTime = new DateTime(2018, 10, 19, 4, 5, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 7, PlayTime = new DateTime(2018, 10, 19, 3, 55, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 8, PlayTime = new DateTime(2018, 10, 19, 3, 16, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 9, PlayTime = new DateTime(2018, 10, 19, 3, 25, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 10, PlayTime = new DateTime(2018, 10, 19, 4, 20, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 11, PlayTime = new DateTime(2018, 10, 19, 4, 1, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 12, PlayTime = new DateTime(2018, 10, 19, 2, 30, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 13, PlayTime = new DateTime(2018, 10, 19, 4, 24, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 14, PlayTime = new DateTime(2018, 10, 19, 3, 49, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 15, PlayTime = new DateTime(2018, 10, 19, 2, 50, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 16, PlayTime = new DateTime(2018, 10, 19, 3, 58, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 17, PlayTime = new DateTime(2018, 10, 19, 2, 25, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 18, PlayTime = new DateTime(2018, 10, 19, 4, 11, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 19, PlayTime = new DateTime(2018, 10, 19, 3, 56, 0, 0, DateTimeKind.Unspecified) },
                        new { AlbumID = 1, SongID = 20, PlayTime = new DateTime(2018, 10, 19, 3, 51, 0, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.AudioFormat", b =>
                {
                    b.Property<int>("AudioFormatID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioFormatName")
                        .IsRequired();

                    b.HasKey("AudioFormatID");

                    b.ToTable("AudioFormats");

                    b.HasData(
                        new { AudioFormatID = 1, AudioFormatName = "Audio CD" },
                        new { AudioFormatID = 2, AudioFormatName = "MP3" },
                        new { AudioFormatID = 3, AudioFormatName = "FLAC" },
                        new { AudioFormatID = 4, AudioFormatName = "WMA" },
                        new { AudioFormatID = 5, AudioFormatName = "WAV" },
                        new { AudioFormatID = 6, AudioFormatName = "OGG" }
                    );
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.Performer", b =>
                {
                    b.Property<int>("PerformerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PerformerName")
                        .IsRequired();

                    b.HasKey("PerformerID");

                    b.ToTable("Performers");

                    b.HasData(
                        new { PerformerID = 1, PerformerName = "Boney M" }
                    );
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.PerformerSong", b =>
                {
                    b.Property<int>("PerformerID");

                    b.Property<int>("SongID");

                    b.HasKey("PerformerID", "SongID");

                    b.HasIndex("SongID");

                    b.ToTable("PerformerSongs");

                    b.HasData(
                        new { PerformerID = 1, SongID = 1 },
                        new { PerformerID = 1, SongID = 2 },
                        new { PerformerID = 1, SongID = 3 },
                        new { PerformerID = 1, SongID = 4 },
                        new { PerformerID = 1, SongID = 5 },
                        new { PerformerID = 1, SongID = 6 },
                        new { PerformerID = 1, SongID = 7 },
                        new { PerformerID = 1, SongID = 8 },
                        new { PerformerID = 1, SongID = 9 },
                        new { PerformerID = 1, SongID = 10 },
                        new { PerformerID = 1, SongID = 11 },
                        new { PerformerID = 1, SongID = 12 },
                        new { PerformerID = 1, SongID = 13 },
                        new { PerformerID = 1, SongID = 14 },
                        new { PerformerID = 1, SongID = 15 },
                        new { PerformerID = 1, SongID = 16 },
                        new { PerformerID = 1, SongID = 17 },
                        new { PerformerID = 1, SongID = 18 },
                        new { PerformerID = 1, SongID = 19 },
                        new { PerformerID = 1, SongID = 20 }
                    );
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SongLiryc");

                    b.Property<string>("SongTitle")
                        .IsRequired();

                    b.HasKey("SongID");

                    b.ToTable("Songs");

                    b.HasData(
                        new { SongID = 1, SongTitle = "Rivers of Babylon" },
                        new { SongID = 2, SongTitle = "Daddy Cool" },
                        new { SongID = 3, SongTitle = "Sunny" },
                        new { SongID = 4, SongTitle = "Brown Girl in the Ring" },
                        new { SongID = 5, SongTitle = "Rasputin" },
                        new { SongID = 6, SongTitle = "Ma Baker" },
                        new { SongID = 7, SongTitle = "Hooray! Hooray! It's A Holi-holiday" },
                        new { SongID = 8, SongTitle = "Painter Man" },
                        new { SongID = 9, SongTitle = "Belfast" },
                        new { SongID = 10, SongTitle = "No Woman, No Cry" },
                        new { SongID = 11, SongTitle = "Mary's Boy Child / Oh My Lord" },
                        new { SongID = 12, SongTitle = "Gotta Go Home" },
                        new { SongID = 13, SongTitle = "Still I'm Sad" },
                        new { SongID = 14, SongTitle = "Nightflight to Venus" },
                        new { SongID = 15, SongTitle = "Felicidad" },
                        new { SongID = 16, SongTitle = "El Lute" },
                        new { SongID = 17, SongTitle = "Baby Do You Wanna Bump" },
                        new { SongID = 18, SongTitle = "Kalimba De Luna" },
                        new { SongID = 19, SongTitle = "Happy Song" },
                        new { SongID = 20, SongTitle = "Megamix" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.Album", b =>
                {
                    b.HasOne("MediaLibrary.Models.Audio.AudioFormat", "AlbumFormat")
                        .WithMany()
                        .HasForeignKey("AlbumFormatAudioFormatID");
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.AlbumSong", b =>
                {
                    b.HasOne("MediaLibrary.Models.Audio.Album", "Album")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaLibrary.Models.Audio.Song", "Song")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaLibrary.Models.Audio.PerformerSong", b =>
                {
                    b.HasOne("MediaLibrary.Models.Audio.Performer", "Performer")
                        .WithMany("PerformerSongs")
                        .HasForeignKey("PerformerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaLibrary.Models.Audio.Song", "Song")
                        .WithMany("PerformerSongs")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
